name: Generate and Push Multi-Profile Trades and Market Pulse

on:
  schedule:
    - cron: '0 13 * * *'
  workflow_dispatch:

jobs:
  generate-trades:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install openai

      - name: Run multi-profile trade generator with market pulse
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python generate_trades.py

      - name: Commit and push JSON files
        run: |
          git config user.name "auto-bot"
          git config user.email "bot@trading.ai"
          git add live_trades_*.json usage_report.json market_pulse.json system_metrics.json
          git commit -m "Daily trade, market pulse, and usage report update"
          git push
