name: Generate and Push Multi-Profile Trades

on:
  schedule:
    - cron: '0 13 * * *'  # Runs daily at 6 AM PST
  workflow_dispatch:         # Allows manual trigger from GitHub Actions tab

jobs:
  generate-trades:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install openai

      - name: Run multi-profile trade generator
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python generate_trades.py

      - name: Commit and push JSON files
        run: |
          git config user.name "auto-bot"
          git config user.email "bot@trading.ai"
          git add live_trades_*.json
          git commit -m "Daily multi-profile trade updates"
          git push
